name=CasicGNSS
version=0.0.0
author="Colin O'Flynn"
maintainer="Colin O'Flynn"
sentance=Small Arduino library for parsing the CASIC GNSS binary protocol.
paragraph=This protocol is used for communicating with certain low-cost GNSS modules including those based around the AT6558 processor.
category=Sensors
url=https://github.com/colinoflynn/arduino-casic-gnss-zhk
architectures=*
